//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamadosImpressora.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbChamadosImpressoraEntities : DbContext
    {
        public dbChamadosImpressoraEntities()
            : base("name=dbChamadosImpressoraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCategoriaChamado> tblCategoriaChamado { get; set; }
        public virtual DbSet<tblDepartamento> tblDepartamento { get; set; }
        public virtual DbSet<tblImpressora> tblImpressora { get; set; }
        public virtual DbSet<tblLocacao> tblLocacao { get; set; }
        public virtual DbSet<tblRegistroChamados> tblRegistroChamados { get; set; }
        public virtual DbSet<tblSeccional> tblSeccional { get; set; }
        public virtual DbSet<tblStatus> tblStatus { get; set; }
    
        public virtual ObjectResult<spBuscaCategoriaChamado_Result> spBuscaCategoriaChamado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBuscaCategoriaChamado_Result>("spBuscaCategoriaChamado");
        }
    
        public virtual ObjectResult<spBuscaDepartamentosPorSeccional_Result> spBuscaDepartamentosPorSeccional(Nullable<int> iD_Seccional)
        {
            var iD_SeccionalParameter = iD_Seccional.HasValue ?
                new ObjectParameter("ID_Seccional", iD_Seccional) :
                new ObjectParameter("ID_Seccional", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBuscaDepartamentosPorSeccional_Result>("spBuscaDepartamentosPorSeccional", iD_SeccionalParameter);
        }
    
        public virtual ObjectResult<spBuscaImpressorasPorDepartamento_Result> spBuscaImpressorasPorDepartamento(Nullable<int> iD_Seccional, Nullable<int> iD_Departamento)
        {
            var iD_SeccionalParameter = iD_Seccional.HasValue ?
                new ObjectParameter("ID_Seccional", iD_Seccional) :
                new ObjectParameter("ID_Seccional", typeof(int));
    
            var iD_DepartamentoParameter = iD_Departamento.HasValue ?
                new ObjectParameter("ID_Departamento", iD_Departamento) :
                new ObjectParameter("ID_Departamento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBuscaImpressorasPorDepartamento_Result>("spBuscaImpressorasPorDepartamento", iD_SeccionalParameter, iD_DepartamentoParameter);
        }
    
        public virtual ObjectResult<spBuscaSeccionais_Result> spBuscaSeccionais()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBuscaSeccionais_Result>("spBuscaSeccionais");
        }
    
        public virtual ObjectResult<spConsultaChamados_Result> spConsultaChamados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaChamados_Result>("spConsultaChamados");
        }
    
        public virtual ObjectResult<spConsultaChamadosPorId_Result> spConsultaChamadosPorId(Nullable<int> iD_Chamado)
        {
            var iD_ChamadoParameter = iD_Chamado.HasValue ?
                new ObjectParameter("ID_Chamado", iD_Chamado) :
                new ObjectParameter("ID_Chamado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaChamadosPorId_Result>("spConsultaChamadosPorId", iD_ChamadoParameter);
        }
    
        public virtual ObjectResult<spConsultaChamadosPorNomeSeccional_Result> spConsultaChamadosPorNomeSeccional(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaChamadosPorNomeSeccional_Result>("spConsultaChamadosPorNomeSeccional", nomeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spFinalizaChamado(Nullable<int> iD_Chamado, string observacao)
        {
            var iD_ChamadoParameter = iD_Chamado.HasValue ?
                new ObjectParameter("ID_Chamado", iD_Chamado) :
                new ObjectParameter("ID_Chamado", typeof(int));
    
            var observacaoParameter = observacao != null ?
                new ObjectParameter("Observacao", observacao) :
                new ObjectParameter("Observacao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spFinalizaChamado", iD_ChamadoParameter, observacaoParameter);
        }
    
        public virtual int spRegistraChamado(Nullable<int> iD_Chamado, Nullable<int> iD_Seccional, Nullable<int> iD_Departamento, Nullable<int> iD_Impressora, Nullable<int> iD_CategoriaChamado, string descricaoChamado)
        {
            var iD_ChamadoParameter = iD_Chamado.HasValue ?
                new ObjectParameter("ID_Chamado", iD_Chamado) :
                new ObjectParameter("ID_Chamado", typeof(int));
    
            var iD_SeccionalParameter = iD_Seccional.HasValue ?
                new ObjectParameter("ID_Seccional", iD_Seccional) :
                new ObjectParameter("ID_Seccional", typeof(int));
    
            var iD_DepartamentoParameter = iD_Departamento.HasValue ?
                new ObjectParameter("ID_Departamento", iD_Departamento) :
                new ObjectParameter("ID_Departamento", typeof(int));
    
            var iD_ImpressoraParameter = iD_Impressora.HasValue ?
                new ObjectParameter("ID_Impressora", iD_Impressora) :
                new ObjectParameter("ID_Impressora", typeof(int));
    
            var iD_CategoriaChamadoParameter = iD_CategoriaChamado.HasValue ?
                new ObjectParameter("ID_CategoriaChamado", iD_CategoriaChamado) :
                new ObjectParameter("ID_CategoriaChamado", typeof(int));
    
            var descricaoChamadoParameter = descricaoChamado != null ?
                new ObjectParameter("DescricaoChamado", descricaoChamado) :
                new ObjectParameter("DescricaoChamado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRegistraChamado", iD_ChamadoParameter, iD_SeccionalParameter, iD_DepartamentoParameter, iD_ImpressoraParameter, iD_CategoriaChamadoParameter, descricaoChamadoParameter);
        }
    }
}
